name: Tokenlist Validation CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tokenlist-validation:
    name: Tokenlist Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Run validations
        run: |
          ./.github/workflows/validate.sh

      - name: Report Status
        if: always()
        run: echo "Validation completed"
